<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ3xg0Dp\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ3xg0Dp/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQ3xg0Dp.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQ3xg0Dp\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQ3xg0Dp\App_KernelTestDebugContainer([
    'container.build_hash' => 'Q3xg0Dp',
    'container.build_id' => '7a104817',
    'container.build_time' => 1706860449,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ3xg0Dp');
