<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZbgbVlR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZbgbVlR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZbgbVlR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZbgbVlR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZbgbVlR\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZbgbVlR',
    'container.build_id' => '510a1c0e',
    'container.build_time' => 1706867707,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZbgbVlR');
